---
- name: Copy wallpaper to remote system
  vars:
    wallpaper_user: your_target_username
    wallaper_local_path: "files/background.jpg"
    wallpaper_remote_path: "/home/{{ wallpaper_user }}/Pictures/background.jpg"
  ansible.builtin.copy:
    src: "{{ wallpaper_local_path }}"
    dest: "{{ wallpaper_remote_path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  become: yes
  become_user: "{{ wallpaper_user }}"

- name: Set wallpaper using gsettings
  vars:
    wallpaper_user: your_target_username
    wallaper_local_path: "files/background.jpg"
    wallpaper_remote_path: "/home/{{ wallpaper_user }}/Pictures/background.jpg"
  ansible.builtin.command:
    cmd: "gsettings set org.gnome.desktop.background picture-uri 'file://{{ wallpaper_remote_path }}'"
  environment:
    DISPLAY: ":0"
    XAUTHORITY: "/home/{{ wallpaper_user }}/.Xauthority"
  become: yes
  become_user: "{{ wallpaper_user }}"
  when: ansible_facts['distribution'] == 'Kali'
