---
- name: Copy wallpaper to remote system
  ansible.builtin.copy:
    src: "{{ wallpaper_local_path }}"
    dest: "{{ wallpaper_remote_path }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0644'
  become: yes
  become_user: "{{ wallpaper_user }}"

- name: Set wallpaper using gsettings
  ansible.builtin.command:
    cmd: "gsettings set org.gnome.desktop.background picture-uri 'file://{{ wallpaper_remote_path }}'"
  environment:
    DISPLAY: ":0"
    XAUTHORITY: "/home/{{ wallpaper_user }}/.Xauthority"
  become: yes
  become_user: "{{ wallpaper_user }}"
  when: ansible_facts['distribution'] == 'Kali'
