---
- name: "Customizing vm"
  hosts: localhost
  connection: local
  roles:
    - role: install-tools
    - role: configure-tmux
    - role: customize-vim
    - role: customize-terminal
    - role: customize-browser
    - role: gantsign.visual-studio-code
    - role: configure-wallpaper