---
- name: "Install Zsh"
  apt:
    name: zsh
    state: present
  become: true
  become_method: sudo

- name: "Install Git"
  apt:
    name: git
    state: present
  become: true
  become_method: sudo

- name: Copy .p10k.zsh to home
  copy:
    src: "{{ role_path }}/files/.p10k.zsh"
    dest: "{{ ansible_env.HOME }}"
    mode: '0644'