- name: Get groups for old user
  shell: groups {{ old_user }} | cut -d ':' -f2 | xargs -n1 echo
  register: groups
  changed_when: false

- name: Create new user with home directory and groups
  user:
    name: "{{ new_user }}"
    password: "{{ new_password }}"
    group: "{{ new_user_primary_group | default(omit) }}"
    groups: "{{ groups.stdout_lines | join(',') }}"
    append: yes
    create_home: yes
  register: new_user_created

- name: Copy home directory from old to new user
  command: cp -a /home/{{ old_user }}/ /home/{{ new_user }}/
  when: new_user_created.changed

- name: Set ownership of the home directory to the new user
  file:
    path: "/home/{{ new_user }}"
    owner: "{{ new_user }}"
    group: "{{ new_user_primary_group | default(new_user) }}"
    recurse: yes
  when: new_user_created.changed

- name: Delete old user without removing home directory
  user:
    name: "{{ old_user }}"
    state: absent
    remove: no
  when: new_user_created.changed
